/**
 * Task-Api
 *      This document describes the REST API for Task.     # Version Notes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TaskObj { 
    description: string;
    reminder: string;
    due: string;
    category: string;
}

